CREATE TABLE USR_USER (
    USR_ID              VARCHAR(255) NOT NULL,
    USR_DS_USERNAME     VARCHAR(50) UNIQUE NOT NULL,
    USR_DS_PASSWORD     VARCHAR(255) NOT NULL,
    USR_DS_FIRSTNAME    VARCHAR(50) NOT NULL,
    USR_DS_LASTNAME     VARCHAR(50) NOT NULL,
    USR_DS_EMAIL        VARCHAR(50) NOT NULL,
    USR_ST_ACTIVATED    BIT(1)       NOT NULL,
    CONSTRAINT PK_USR_USER PRIMARY KEY (USR_ID)
);

CREATE TABLE AUT_AUTHORITY (
    AUT_ID      VARCHAR(36) NOT NULL,
    AUT_DS_NAME VARCHAR(50) NOT NULL,
    CONSTRAINT PK_AUT_AUTHORITY PRIMARY KEY (AUT_ID));

ALTER TABLE AUT_AUTHORITY
    ADD CONSTRAINT UN_AUT_NAME UNIQUE (AUT_DS_NAME);

CREATE TABLE USA_USER_AUTHORITY(
    USR_ID VARCHAR(255) NOT NULL,
    AUT_ID VARCHAR(255) NOT NULL
);

ALTER TABLE USA_USER_AUTHORITY
    ADD CONSTRAINT FK_USA_USR FOREIGN KEY (USR_ID) REFERENCES USR_USER (USR_ID);

ALTER TABLE USA_USER_AUTHORITY
    ADD CONSTRAINT FK_USA_AUT FOREIGN KEY (AUT_ID) REFERENCES AUT_AUTHORITY (AUT_ID);

CREATE TABLE TKN_TOKEN (
    TKN_ID            VARCHAR(36)  NOT NULL,
    USR_ID            VARCHAR(255) NOT NULL,
    TKN_DH_EXPIRATION DATETIME     NOT NULL,
    TKN_DS_KEY        VARCHAR(255) NOT NULL,
    CONSTRAINT PK_TKN_TOKEN PRIMARY KEY (TKN_ID));

ALTER TABLE TKN_TOKEN
    ADD CONSTRAINT UN_TKN_KEY UNIQUE (TKN_DS_KEY);

ALTER TABLE TKN_TOKEN
    ADD CONSTRAINT FK_TKN_USR FOREIGN KEY (USR_ID) REFERENCES USR_USER (USR_ID);

CREATE TABLE END_ENDERECO (
    END_ID                 VARCHAR(255) NOT NULL,
    END_DS_LOGRADOURO  VARCHAR(255) NULL,
    END_DS_NUMERO      VARCHAR(255) NULL,
    END_DS_COMPLEMENTO VARCHAR(255) NULL,
    END_DS_BAIRRO      VARCHAR(255) NULL,
    END_DS_CIDADE      VARCHAR(255) NULL,
    END_DS_ESTADO      VARCHAR(255) NULL,
    END_DS_CEP         VARCHAR(255) NULL,
    END_DS_OBSERVACAO  VARCHAR(255) NULL,
    CONSTRAINT PK_END_ENDERECO PRIMARY KEY (END_ID)
);

CREATE TABLE TRS_TRANSPORTADOR (
    TRS_ID              VARCHAR(255) NOT NULL,
    TRS_DS_NOME         VARCHAR(255) NULL,
    TRS_DS_RAZAO_SOCIAL VARCHAR(255) NULL,
    TRS_NM_CNPJ         VARCHAR(255) NULL,
    END_ID              VARCHAR(255) NOT NULL,
    TRS_ST_ATIVO        BIT(1)       NOT NULL,
    TRS_DS_TELEFONE     VARCHAR(255) NULL,
    TRS_DS_EMAIL        VARCHAR(255) NULL,
    CONSTRAINT PK_TRS_TRANSPORTADOR PRIMARY KEY (TRS_ID));

ALTER TABLE TRS_TRANSPORTADOR
    ADD CONSTRAINT UN_TRS_CNPJ UNIQUE (TRS_NM_CNPJ);

ALTER TABLE TRS_TRANSPORTADOR
    ADD CONSTRAINT FK_TRS_END FOREIGN KEY (END_ID) REFERENCES END_ENDERECO (END_ID);

CREATE TABLE TDS_TIPO_DESCARTE (
    TDS_ID       VARCHAR(255) NOT NULL,
    TDS_DS_NOME  VARCHAR(255) NOT NULL,
    TDS_VL_PRECO DOUBLE       NOT NULL,
    TDS_ST_ATIVO BIT(1)       NOT NULL,
    CONSTRAINT PK_TDS_TIPO_DESCARTE PRIMARY KEY (TDS_ID));

CREATE TABLE FRP_FORMA_PAGAMENTO (
    FRP_ID       VARCHAR(255) NOT NULL,
    FRP_DS_NOME  VARCHAR(255) NOT NULL,
    FRP_ST_ATIVO BIT(1)       NOT NULL,
    CONSTRAINT PK_FRP_FORMA_PAGAMENTO PRIMARY KEY (FRP_ID));

CREATE TABLE CMB_COMBO (
    CMB_ID       VARCHAR(255) NOT NULL,
    TRS_ID       VARCHAR(255) NOT NULL,
    TDS_ID       VARCHAR(255) NOT NULL,
    CMB_VL_SALDO INT          NOT NULL,
    CMB_ST_ATIVO BIT(1)       NOT NULL,
    CONSTRAINT PK_CMB_COMBO PRIMARY KEY (CMB_ID));

ALTER TABLE CMB_COMBO
    ADD CONSTRAINT FK_CMB_TDS FOREIGN KEY (TDS_ID) REFERENCES TDS_TIPO_DESCARTE (TDS_ID);

ALTER TABLE CMB_COMBO
    ADD CONSTRAINT FK_CMB_TPR FOREIGN KEY (TRS_ID) REFERENCES TRS_TRANSPORTADOR (TRS_ID);

CREATE TABLE AQS_AQUISICAO (
    AQS_ID           VARCHAR(255) NOT NULL,
    CMB_ID           VARCHAR(255) NOT NULL,
    FRP_ID           VARCHAR(255) NOT NULL,
    AQS_QT_ADQUIRIDA INT          NULL,
    AQS_DH_PAGAMENTO DATE         NULL,
    AQS_VL_PAGO      DOUBLE       NULL,
    AQS_VL_DESCONTO  DOUBLE       NULL,
    AQS_ST_ATIVO     BIT(1)       NULL,
    CONSTRAINT PK_AQS_AQUISICAO PRIMARY KEY (AQS_ID));

ALTER TABLE AQS_AQUISICAO
    ADD CONSTRAINT FK_AQS_CMB FOREIGN KEY (CMB_ID) REFERENCES CMB_COMBO (CMB_ID);

ALTER TABLE AQS_AQUISICAO
    ADD CONSTRAINT FK_AQS_FRP FOREIGN KEY (FRP_ID) REFERENCES FRP_FORMA_PAGAMENTO (FRP_ID);

CREATE TABLE GRD_GERADOR (
    GRD_ID              VARCHAR(255) NOT NULL,
    GRD_DS_NOME         VARCHAR(255) NOT NULL,
    GRD_DS_RAZAO_SOCIAL VARCHAR(255) NULL,
    GRD_DS_CNPJ         VARCHAR(255) NULL,
    GRD_DS_CPF          VARCHAR(255) NULL,
    END_ID              VARCHAR(255) NOT NULL,
    GRD_DS_TELEFONE     VARCHAR(255) NULL,
    GRD_DS_EMAIL        VARCHAR(255) NULL,
    GRD_ST_ATIVO        BIT(1)       NOT NULL,
    CONSTRAINT PK_GRD_GERADOR PRIMARY KEY (GRD_ID));

ALTER TABLE GRD_GERADOR
    ADD CONSTRAINT UN_GRD_CNPJ UNIQUE (GRD_DS_CNPJ);

ALTER TABLE GRD_GERADOR
    ADD CONSTRAINT UN_GRD_CPF UNIQUE (GRD_DS_CPF);

ALTER TABLE GRD_GERADOR
    ADD CONSTRAINT FK_GRD_END FOREIGN KEY (END_ID) REFERENCES END_ENDERECO (END_ID);

CREATE TABLE VCL_VEICULO (
    VCL_ID        VARCHAR(255) NOT NULL,
    VCL_DS_MARCA  VARCHAR(255) NOT NULL,
    VCL_DS_MODELO VARCHAR(255) NOT NULL,
    VCL_NM_PLACA  VARCHAR(255) NOT NULL,
    TRS_ID        VARCHAR(255) NOT NULL,
    VCL_ST_ATIVO  BIT(1)       NOT NULL,
    CONSTRAINT PK_VCL_VEICULO PRIMARY KEY (VCL_ID));

ALTER TABLE VCL_VEICULO
    ADD CONSTRAINT UN_VCL_PLACA UNIQUE (VCL_NM_PLACA);

ALTER TABLE VCL_VEICULO
    ADD CONSTRAINT FK_VCL_TRS FOREIGN KEY (TRS_ID) REFERENCES TRS_TRANSPORTADOR (TRS_ID);

CREATE TABLE DST_DESTINATARIO (
    DST_ID              VARCHAR(255) NOT NULL,
    DST_DS_NOME         VARCHAR(255) NOT NULL,
    DST_DS_RAZAO_SOCIAL VARCHAR(255) NULL,
    DST_NM_CNPJ         VARCHAR(18)  NULL,
    DST_NM_TELEFONE     VARCHAR(255)  NULL,
    END_ID              VARCHAR(255) NOT NULL,
    DST_ST_ATIVO        BIT(1)       NOT NULL,
    DST_DS_EMAIL        VARCHAR(255) NULL,
    CONSTRAINT PK_DST_DESTINATARIO PRIMARY KEY (DST_ID));

ALTER TABLE DST_DESTINATARIO
    ADD CONSTRAINT FK_DST_DESTINATARIO_ON_END FOREIGN KEY (END_ID) REFERENCES END_ENDERECO (END_ID);

CREATE TABLE MTR_MOTORISTA (
    MTR_ID          VARCHAR(255) NOT NULL,
    MTR_DS_NOME     VARCHAR(255) NOT NULL,
    MTR_NM_TELEFONE VARCHAR(255) NOT NULL,
    MTR_NM_CNH      VARCHAR(255) NULL,
    CONSTRAINT PK_MTR_MOTORISTA PRIMARY KEY (MTR_ID));

CREATE TABLE CTR_CTR (
    CTR_ID         VARCHAR(255) NOT NULL,
    GRD_ID         VARCHAR(255) NOT NULL,
    VCL_ID         VARCHAR(255) NOT NULL,
    DST_ID         VARCHAR(255) NOT NULL,
    TRS_ID         VARCHAR(255) NOT NULL,
    MTR_ID         VARCHAR(255) NOT NULL,
    CTR_DH_GERACAO DATETIME     NOT NULL,
    CTR_ST_ATIVO   BIT(1)       NULL,
    CONSTRAINT PK_CTR_CTR PRIMARY KEY (CTR_ID));

ALTER TABLE CTR_CTR
    ADD CONSTRAINT FK_CTR_GRD FOREIGN KEY (GRD_ID) REFERENCES GRD_GERADOR (GRD_ID);

ALTER TABLE CTR_CTR
    ADD CONSTRAINT FK_CTR_MTR FOREIGN KEY (MTR_ID) REFERENCES MTR_MOTORISTA (MTR_ID);

ALTER TABLE CTR_CTR
    ADD CONSTRAINT FK_CTR_TRS FOREIGN KEY (TRS_ID) REFERENCES TRS_TRANSPORTADOR (TRS_ID);

ALTER TABLE CTR_CTR
    ADD CONSTRAINT FK_CTR_VCL FOREIGN KEY (VCL_ID) REFERENCES VCL_VEICULO (VCL_ID);

ALTER TABLE CTR_CTR
    ADD CONSTRAINT FK_CTR_DST FOREIGN KEY (DST_ID) REFERENCES DST_DESTINATARIO (DST_ID);

CREATE TABLE CTT_CTR_TIPO_DESCARTE (
    CTR_ID VARCHAR(255) NOT NULL,
    TPS_ID VARCHAR(255) NOT NULL);

ALTER TABLE CTT_CTR_TIPO_DESCARTE
    ADD CONSTRAINT FK_CTT_CTR FOREIGN KEY (CTR_ID) REFERENCES CTR_CTR (CTR_ID);

ALTER TABLE CTT_CTR_TIPO_DESCARTE
    ADD CONSTRAINT FK_CTT_TPS FOREIGN KEY (TPS_ID) REFERENCES TDS_TIPO_DESCARTE (TDS_ID);

CREATE TABLE PGT_PAGAMENTO (
    PGT_ID           VARCHAR(255) NOT NULL,
    PGT_DT_PAGAMENTO DATE         NOT NULL,
    PGT_VL_PRECO     DOUBLE       NOT NULL,
    FRP_ID           VARCHAR(255) NOT NULL,
    PGT_ST_ATIVO     BIT(1)       NOT NULL,
    CTR_ID           VARCHAR(255) NOT NULL,
    CONSTRAINT PK_PGT_PAGAMENTO PRIMARY KEY (PGT_ID));

ALTER TABLE PGT_PAGAMENTO
    ADD CONSTRAINT FK_PGT_CTR FOREIGN KEY (CTR_ID) REFERENCES CTR_CTR (CTR_ID);

ALTER TABLE PGT_PAGAMENTO
    ADD CONSTRAINT FK_PGT_FRP FOREIGN KEY (FRP_ID) REFERENCES FRP_FORMA_PAGAMENTO (FRP_ID);

CREATE TABLE DSC_DESCARTE_POR_COMBO (
    DSC_ID            VARCHAR(255) NOT NULL,
    CMB_ID            VARCHAR(255) NOT NULL,
    CTR_ID            VARCHAR(255) NOT NULL,
    DSC_NM_QUANTIDADE INT          NOT NULL,
    DSC_DH_DESCARTE   DATETIME     NOT NULL,
    CONSTRAINT PK_DSC_DESCARTE_POR_COMBO PRIMARY KEY (DSC_ID));

ALTER TABLE DSC_DESCARTE_POR_COMBO
    ADD CONSTRAINT FK_DSC_CMB FOREIGN KEY (CMB_ID) REFERENCES CMB_COMBO (CMB_ID);

ALTER TABLE DSC_DESCARTE_POR_COMBO
    ADD CONSTRAINT FK_DSC_CTR FOREIGN KEY (CTR_ID) REFERENCES CTR_CTR (CTR_ID);

-- CREATE SEQUENCE USER_SEQ
--    MINVALUE 1
--    MAXVALUE 999999999
--    INCREMENT BY 1
--    START WITH 202700
--    NOCACHE
--    NOCYCLE;
