CREATE TABLE AUT_AUTHORITY(
   ID   VARCHAR(36) PRIMARY KEY,
   NAME VARCHAR(255) UNIQUE
);

CREATE TABLE USR_USER(
   ID        VARCHAR(36) PRIMARY KEY,
   USERNAME  VARCHAR(50)  NOT NULL UNIQUE,
   PASSWORD  VARCHAR(100) NOT NULL,
   FIRSTNAME VARCHAR(50)  NOT NULL,
   LASTNAME  VARCHAR(50)  NOT NULL,
   EMAIL     VARCHAR(50)  NOT NULL UNIQUE,
   ACTIVATED boolean      NOT NULL
);

CREATE TABLE USER_AUTHORITY(
   USER_ID      VARCHAR(36) NOT NULL,
   AUTHORITY_ID VARCHAR(36) NOT NULL,
   FOREIGN KEY (USER_ID) REFERENCES USR_USER (ID),
   FOREIGN KEY (AUTHORITY_ID) REFERENCES AUT_AUTHORITY (ID)
);

CREATE TABLE TOKEN(
   USER_ID VARCHAR(36) NOT NULL,
   USR_ID varchar(36) NOT NULL,
   EXPIRATION DATETIME NOT NULL,
   TOKEN VARCHAR(50) NOT NULL
);



-- CREATE SEQUENCE USER_SEQ
--    MINVALUE 1
--    MAXVALUE 999999999
--    INCREMENT BY 1
--    START WITH 202700
--    NOCACHE
--    NOCYCLE;
